#FROM node:22-alpine
#
#WORKDIR /app
#
#COPY package*.json ./
#
#RUN npm install
#
#COPY . .
#
#RUN npm run build
#
#EXPOSE 4173
#
##CMD ["npm","run","preview"]
#CMD ["npm","run","preview","--","--host","0.0.0.0","--port","4173"]

##============================== Stage 1 starts

FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

##============================= Stage 2 starts

FROM node:22-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist

COPY --from=builder /app/package*.json ./

RUN npm install

CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0"] 
